[package]
name = "wordle_kernel"
version = "0.1.0"
edition = "2024"

[dependencies]
embedded-graphics = "0.8.1"
limine = "0.5.0"

[profile.kernel]
inherits = "release"
opt-level = "s"
lto = true
codegen-units = 1
debug = false
overflow-checks = false
panic = "abort"
