version = 1

[[annotations]]
path = [
    ".cargo/config.toml",
    ".gitignore",
    "Cargo.lock",
    "Cargo.toml",
    "limine/limine.conf",
    "rust-toolchain.toml",
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"
